### ISSUE TITLE
Check results returned before loop completed

### ISSUE THREAD

**Issue by vsoch** [urlstechie/urlchecker-action#16]
I'm not sure if this is intentional, but the list of check_results is returned after just parsing one of the urls in the list:

https://github.com/urlstechie/URLs-checker/blob/3200baf59d73c3e8c0fd92e9ce73c375603b4b2b/core/urlproc.py#L59

Assuming that there is one list of urls, wouldn't we want to go through all of them, update check_results as we go, and return the final two lists? I'm working on a PR now, I can update this to fix the issue (if it isn't intentional!)

**Comment by SuperKogito** [comment]
You are totally right :+1:  That return should be outside of the for loop. That explains some of the weird behaviours mentioned in #8. I will be looking to your PR.
