### ISSUE TITLE
Missing parameter for recent retry update

### ISSUE THREAD

**Issue by vsoch** [urlstechie/urlchecker-action#18]
I'm going to open a PR to fix this ASAP

```
 buildtest-framework/README.rst 
 ------------------------------
Traceback (most recent call last):
  File "/check.py", line 99, in <module>
    check_results = check_repo(file_paths, print_all, white_listed_urls,
  File "/check.py", line 71, in check_repo
    check_results = urlproc.check_urls(file, urls, retry_count, timeout)
  File "/core/urlproc.py", line 99, in check_urls
    do_retry = check_response_status_code(response, print_format)
TypeError: check_response_status_code() missing 1 required positional argument: 'print_format'
```
I wish GitHub actions had some way to check this outside of actions.

**Comment by SuperKogito** [comment]
The good thing about our code structure is that you can use the pytests for that or use the check.py in offline mode. By offline mode here, I mean to comment the env variables at the beginning and replace them with some hard coded variables or even better variables read from a config file and that way you can run tests on your machine on any GitHub repo you want.

**Comment by vsoch** [comment]
Just finished work - all looks good! I'll open a PR right now - there were some other changes I made to make the interface easier to see failures, etc. Stay tuned!

**Comment by vsoch** [comment]
This is now fixed!
