### ISSUE TITLE
Improving tests

### ISSUE THREAD

**Issue by vezeli** [urlstechie/urlchecker-action#2]
Consider making tests including e-mail addresses or maybe you made them somewhere but I missed them. As you know, there are corner-stone cases when using regular expressions so it is good to find them :) 

Maybe take a look at this [repo](https://github.com/lipoja/URLExtract) and tests, although this one is not bulletproof either https://github.com/lipoja/URLExtract/issues/13.

**Comment by SuperKogito** [comment]
So when it comes to improving the tests and making them more elaborate, I totally agree. The current tests are just something to start with and I was counting on issues and bug reports to improve them. However, your point about e-mails is not clear to me. The purpose of this action/ library is essentially to extract URLs from a project and check if they are reachable, which is not applicable to e-mails. What you linked and based on some research I did, all I can do is extract e-mails and validate their format which seems to be a bit of context here, don't you think ?

**Comment by vezeli** [comment]
Oh sorry, I didn't explain my self well. I didn't mean to say to ping e-mail addresses. I meant to say that it is not easy to get a good and reliable URL extractor and that URL extractor is a core part of ULRs-checker. About e-mail, e-mails can have similar structures like URLs, especially in the domain part of the email address which could be wrongly taken for a URL.

For example, I went to https://regex101.com/ and tested briefly the regular expression in the URLs-checker for some made-up (but possible) email addresses "fake-group@info.findly.io". In this particular case, if this e-mail address was for some reason inside a project, "findly.io" would be considered as a valid URL. In turn, the URLs-checker would faulty check this URL for existence and maybe report an error.

Having these tests for different examples of e-mail addresses would help because it would show where the URLs-checker is working properly and where it needs more improvements and others would be more convinced to use it.

**Comment by SuperKogito** [comment]
I get it now. You make a very good point here. I will seek to cover this in the next releases.

**Comment by SuperKogito** [comment]
I just implemented a new whitelisting feature and tried to diversify the tests and improve them. email addresses do not seem to pose a problem but I would appreciate it, if you can take a look at the new version and let me what you think of it :)

**Comment by SuperKogito** [comment]
fixed in e467d3f0c61952abb6892d351c9f50e1f2cff935 with 91% coverage
