### ISSUE TITLE
Export results to a file and commit it to git repo

### ISSUE THREAD

**Issue by SuperKogito** [urlstechie/urlchecker-action#23]
A possible improvement is to export the checks results into a `.txt` report that will be committed to the folder.

**Comment by vsoch** [comment]
This should be optional I think - likely there will be users that want the report just for the interface, and others for other actions to handle (it would be treated as an output param for some next action).

**Comment by SuperKogito** [comment]
I agree, this should be optional.

**Comment by vsoch** [comment]
This is implemented, the user can add the "save" argument to save results to file.
