### ISSUE TITLE
Add white listed files and patterns variable

### ISSUE THREAD

**Issue by vsoch** [urlstechie/urlchecker-action#27]
Currently, I can add _config.yml and README.md to my white_listed_patterns, but the files /github/workspace/_config.yml and /github/workspace/README.md are still checked. I suspect it's looking for the full path or starts with, and as a user I'd expect it to do more of a re.search (using my pattern). E.g., this should work without /github/workspace

```
        # Cannot check private GitHub settings
        white_listed_patterns: _config.yml,README.md,SocialNetworks.yml,.github/workflows,tests
```

**Comment by vsoch** [comment]
It also appears that doesn't work with the full paths - I'm going to try adding these paths to the white list explicitly.

**Comment by vsoch** [comment]
Ah actually I am mistaken here - the patterns are for the URLs of course! What we need is a pattern for the _files_ as well, something like:

```
white_listed_files: _config.yml
white_listed_file_patterns: _config.yml
```

**Comment by vsoch** [comment]
I have good examples of generating these newlines so I'm assigning myself to figure it out.

**Comment by vsoch** [comment]
Update here - we don't need patterns AND files, we can just add `white_listed_files` and then do a regular expression search with a giant OR of all patterns. This would work for a direct / complete file path OR a regular expression for it.

**Comment by SuperKogito** [comment]
Can you please elaborate on why we don't need files AND patterns, as I actually would like to have both for the sake of consistency (since we do the same with links).

**Comment by vsoch** [comment]
re.search() can handle both. It would be redundant. Can you give me an example where that would not work?

**Comment by SuperKogito** [comment]
It is just an intuition but I am not sure. We can simply merge and test it.
