### ISSUE TITLE
black linting

### ISSUE THREAD

**Issue by vsoch** [urlstechie/urlchecker-action#29]
@SuperKogito what are your thoughts on adding black for code formatting? It will be easier to enforce a standard for code style, and make the code a bit easier to read. We are doing a fairly good job of keeping it need, but some of the sections with input arguments are a bit crunched and would benefit from black. There are a few levels we can add it:

 - enforced as check with GitHub workflow action (and message to user if it fails with instructions to run it)
 - done locally, but not enforced

Let me know your thoughts! I'm working on the two issues I opened this morning now, but if you like the idea of black I can do a PR with a workflow for that after.

**Comment by SuperKogito** [comment]
I am currently using codacy to keep an eye on the quality. Please check this link: https://app.codacy.com/gh/orgs/urlstechie/dashboard
Codacy uses Pylint which follows the style recommended by PEP 8. I have seen black used in a couple of projects and it seems to be getting attention, but what additional advantages would that give us?

**Comment by vsoch** [comment]
No you're totally right - the checks you are running work great (I didn't see them before). My one concern is with coverage, because if we put params on more lines so it reads more cleanly, that seems to decrease it. Anyway, let's close the issue here because we don't need black.
