### ISSUE TITLE
Whitelist urls

### ISSUE THREAD

**Issue by tinova** [urlstechie/urlchecker-action#3]
For instance "https://x.x.x.x/mob/?moid=yyyyy" is an example URL and shouldn't give a warning (it would be nice to be able to curate a whitelist of URLs in the action conf file)

**Comment by SuperKogito** [comment]
Whitelisting URLs or patterns (based on included text, or base link) is now available. I would appreciate it if you can take a look at the Readme and let me know what you think of it?
