### ISSUE TITLE
When python library exists, consider renaming for action

### ISSUE THREAD

**Issue by vsoch** [urlstechie/urlchecker-action#34]
When we have more than one repository (this one here) and we refactor the action, we might possibly want to consider renaming this repository (while it's still early and we can track down users and make sure they update names) to something that strongly indicates "I'm a GitHub action." E.g.,

 - urlschecker-python: --> deploys urlschecker python module
 - urlschecker-action -> GitHub action

And then the namespace is a bit more clear.

**Comment by SuperKogito** [comment]
I agree, I have been having thoughts about that actually because I am not comfortable with uppercase letters. What about the organization name? any thoughts about that?

**Comment by vsoch** [comment]
I am not a fan of the uppercase letters either! I think urlstechie is nice, urlchecker is already taken, and urlschecker isn't, but "techie" is shorter, and also gives more freedom to write different kinds of tools for generally working with urls (beyond checking). If you aren't content with it I can try to think about other options, but I think it's a pretty good choice :) If you want something shorter (along the same lines) it looks like https://github.com/urltech is available. There are actually quite a few short ones with url included that get at the same thing

 - https://github.com/urlslab
 - https://github.com/urlteam
 - https://github.com/urlchecks
 - https://github.com/urltools
 - https://github.com/urlstat
 - https://github.com/urlsrus "URLS r us", like Toys r us, ha
 - https://github.com/urlsaurus sounds like a dinosaur (could be cute logo)
 - https://github.com/uarels (sounds like urls)
 - https://github.com/urlls

Most of those are fairly bad, haha. I'll keep thinking! Something that also affords good branding is always nice.

**Comment by SuperKogito** [comment]
This is a great list actually, I think we have the same ideas. I am okay with urlstechie but  I needed some confirmation and a different opinion. I also mentioned it just so you know that i am open to do name changes if needed/ if something better is available. For now urlstechie seems to be cool enough.
I will change the action name to `urlschecker-action` in the next release as it seems more informative.

**Comment by vsoch** [comment]
One quick additional point to discuss - for the python module, I was thinking `urlchecker` would be shorter, more succinct than `urlschecker`. Do you have preference over urls vs url for the prefix?

**Comment by SuperKogito** [comment]
btw did you check for those names manually or using some tool? cuz that seems to be a cool useful tool to implement if it doesn't exist lol

**Comment by vsoch** [comment]
Haha, I just manually went to the pages and looked for 404s. I also sometimes (when I'm creating an org) just use the GitHub page to create/name, and it updates dynamically with a red X or green check if it's available. So probably they already have that implemented internally.

**Comment by SuperKogito** [comment]
I do not have a preference urlschecker seemed easier on the ear (at least mine). To your point, I think shorter/simpler is better, so if you think it is better we can make the change. I was also thinking of `ucheck` or `uchecker` ?

**Comment by vsoch** [comment]
I do think we need to preserve url in it's entirety, if I heard something like "ucheck" I'd respond "Who, what, me?" :P

**Comment by SuperKogito** [comment]
lol, `urlchecker-python` and `urlchecker-action`it is then?

**Comment by vsoch** [comment]
That sounds good to me!

**Comment by vsoch** [comment]
We're ready for rename! `urlchecker-action` it is!
