### ISSUE TITLE
Consider removing docs folder

### ISSUE THREAD

**Issue by vsoch** [urlstechie/urlchecker-action#37]
I don't think it's relevant here anymore - it's completely represented in https://github.com/urlstechie/urlchecker-python. I wasn't 100% sure so I didn't want to delete.

**Comment by SuperKogito** [comment]
I think you are right. I will take it down :+1:

**Comment by vsoch** [comment]
okay I opened a PR that will remove #38 - when that is merged we can close here.

**Comment by SuperKogito** [comment]
merged :+1:
