### ISSUE TITLE
Some URLs break verification

### ISSUE THREAD

**Issue by tinova** [urlstechie/urlchecker-action#4]
Feel free to take a look at: https://github.com/tinova/docs/runs/335326174

**Comment by SuperKogito** [comment]
I think whitelisting these type of links is a possible solution to apply. This will be available the next release that I will publish once I am done testing, unless you have better suggestions on how to handle these?

**Comment by SuperKogito** [comment]
consider upgrading to the latest version of URLs-chercker. These breaks should be solved. Feel free to re-open this if it is not the case but also please post the logs ;)
