### ISSUE TITLE
fix 0.1.8 to use urlchercker 0.1.14

### ISSUE THREAD

**Issue by SuperKogito** [urlstechie/urlchecker-action#41]
@vsoch  I updated, fixed some bugs and tested urlchecker-python. I also automated the quay.io docker builds and released a new version on pypi 0.1.14. I edited the action to use this version and tested it on https://github.com/urlstechie/urlchecker-test-repo/ but it is failing, I am not sure what did I miss and since you are more familiar with the new structure, can you please take a look ? Here are the logs: https://github.com/urlstechie/urlchecker-test-repo/runs/562209780?check_suite_focus=true

**Comment by vsoch** [comment]
You introduced a bug by changing Boolean arguments to be strings with default of False, eg   "--cleanup" should have a store_true. This version you just released is entirely broken so I suggest you revert it back and re release, and please let me review next time before you make such changes :/

**Comment by vsoch** [comment]
You broke the client so I think you should be the one to fix it, if you revert back to how it was you should be fine. The extra code you added for the parser seems excessive - it is already setup to handle Boolean arguments. A flag is either present or not, the user does not provide “True” of “False” on the command line. I’m a little upset about this so I hope that you can take charge to fix it.

**Comment by SuperKogito** [comment]
I did not like the `store_true`alternative because the input was confusing and not consistent. For example: 
using `store_true`: I had to call: `urlchecker check . --subfolder=tests true ...` in this case the use should assume which variable he is assigning and maintain the order which is not very flexible, don't you think? 
but in the new version: I can write : `urlchecker check . --subfolder=tests cleanup=true ... 
which I find more consistent and easier for users.`
Entirely broken? how? :o I am pretty sure that I tested it. I think I must be missing something here?

**Comment by vsoch** [comment]
That is how boolean variables work to provide a flag. Flags are standard in command line software and no user is going to expect to write --flag "True" it's not logical.

**Comment by SuperKogito** [comment]
Okay. I will take your word for it. But then I will add some more documentation because it was confusing to me personally.

**Comment by vsoch** [comment]
Sure thing! More documentation is fine, but I can guarantee you that most of the command line using world is not used to seeing boolean flags represented with `--cleanup true`. The boolean is also provided to the function, e.g., `cleanup=True` and not "cleanup="true"" that then needs to be parsed into a boolean. I think you are confused because the GitHub action has the user specify true and we have to check that and add the flag. I need to look at how you modified the action next and fix that up. No worries about the misunderstanding, please be careful next time, we absolutely cannot release broken software :)

**Comment by SuperKogito** [comment]
I can revert all the fixes. It will probably be easier since I messed them up. I will revert my fixes (*mistakes) and let you know ;)

**Comment by vsoch** [comment]
I already fixed them! Don't do anything it's fixed.

**Comment by vsoch** [comment]
Do you mean in the action? I haven't looked at that yet (I was talking about urlchecker-python). Sorry I'm a bit anxious. :/

**Comment by SuperKogito** [comment]
it is okay, no worries. I will let you deal with the python module and I will submit a PR later if something is still there. I need to fix the action cuz I guess somehow I managed to break it all today.

**Comment by vsoch** [comment]
I think we're fixed - the action is working again, and urlchecker python has working containers and pypi release. I'm going to close the issue here, and try to go back to try and relax a little this morning, and catch up with the work I needed to do.
