### ISSUE TITLE
Can the URL checks run on the files added/edited by a PR only?

### ISSUE THREAD

**Issue by maelle** [urlstechie/urlchecker-action#44]
Sorry for asking without trying first!

I found this repo via https://vsoch.github.io/2020/urlchecker/, it looks really cool 👏

**Comment by maelle** [comment]
For context I was thinking that for a website I'd probably set a CRON job (monthly or so) to check all files whereas in a PR I'd be interested in new files, maybe with a check run depending on PR comments like https://github.com/tidyverse/ggplot2/blob/master/.github/workflows/pr-commands.yaml 

Anyway, looking forward to trying this out.

**Comment by vsoch** [comment]
hey @maelle - you could definitely have the trigger happen by way of a scheduled github workflow (akin to a cron job) that checks your repository every so often for broken links, and also it's useful to have the same function happen in a PR. We don't currently have any kind of flag that checks files based on a timestamp, but we do have whitelisted patterns that would skip. If a timestamp check would be useful to you, can you give me an example of how you'd like the UI to work? We would first add it to [urlchecker-python](https://github.com/urlstechie/urlchecker-python) and then wrap it here. E.g., would you imagine something like:

```bash
urlchecker check --date-before YYYY-MM-DD .
```
And what flags would make sense to have, date before? date after? updated-after? updated-before? let me know what you think and we can work on it! Also, there are several examples that might help you to get started in https://github.com/urlstechie/urlchecker-action/tree/master/examples. If you wind up making an example that you like, I hope that you consider contributing there! I can also offer to help if you have any issues.

**Comment by maelle** [comment]
Thank you!!

In a PR I was thinking maybe some sort of git magic would reveal which files are "touched" by the PR?

**Comment by vsoch** [comment]
You could try for that, but it would at best be a hack (I've tried doing similar with grepping output from git and it's not as reliable as I'd want). But if you instead used git log to get the last commit from some branch (let's say master):

```
 git log master -1 --date=iso
```
You could then parse that to get the date:

```bash
$ git log master -1 --date=iso | grep Date: | cut -d' ' -f4
2019-10-30
```
And that could be piped to the command:

```bash
LAST_UPDATED=$(git log master -1 --date=iso | grep Date: | cut -d' ' -f4)
urlchecker check --since "${LAST_UPDATED}"
```
And we could then have a since argument for the action to set some hard date, and this would be set in some previous step and piped into the run.
```
 since: 2020-01-01
```
What do you think?

**Comment by maelle** [comment]
Yes, that's a good workaround! :pray: 

Out of curiosity, why is using git less reliable than you'd want? And how does GitHub show which files were edited?

**Comment by vsoch** [comment]
Well, without a flag like I suggested, how would you implement this?

**Comment by maelle** [comment]
passing file paths directly to the checker? but I'm really naive as to what's possible with the git log.

**Comment by vsoch** [comment]
Actually that’s a good option too! If we had an explicit option to check a specific file (or pattern that could also be direct path to a file), you could loop through some set and check for each one. That might be more useful than the hard coded date idea. I’m going to bed now but if this would be useful to you I can work on it soon.

**Comment by maelle** [comment]
I think yes it'd be useful but not urgent.

Working on the CRON job for a site now :-) Good night and thank you!

**Comment by maelle** [comment]
For info, monthly checks: https://github.com/maelle/simplymaelle/blob/master/.github/workflows/main.yml, thank you :-)

**Comment by maelle** [comment]
Not related to url checks (and not expecting an answer now), there's no way to set up GitHub actions notifications settings by repo, too bad (for most repos I only want notifications for failed runs). Ideally the URL checks would run once a month and then I'd get a notification that it passed, so I'd remember to go look at the log. At the moment I think that I'd need a calendar reminder to go with my CRON job.

Anyway I'm very glad I read about this action, this is super useful, thank you.

**Comment by SuperKogito** [comment]
**I just want to answer your initial question:** 
So this is theoretically possible but it will need you to construct your own workflow that will pass some variables to urlchecker. With the action current format, there is no straight forward solution. 
I suggest using the following [post](https://stackoverflow.com/questions/41139485/how-can-i-see-all-modified-files-from-a-git-pull-request) to get the files changed in the PR. Also make sure to combine the previous git command with the command mentioned [here](https://unix.stackexchange.com/questions/338116/turning-separate-lines-into-a-comma-separated-list-with-quoted-entries) to format the output, which you will use as an input to the urlchecker. 

On the other hand, I think we , @vsoch , need to add an option where the user can specify for which files he want to run the checks. In case the user want to check only one or two files.  Something similar to `--subfolder`, maybe `--files`. 

If this cannot wait for the next release, the previous steps can be used in Bash to make a list of whitelisted files, that will work with the current version of the action or the python package, but it can be ugly cuz it is going to be a long list I assume.

**Comment by SuperKogito** [comment]
In this link https://help.github.com/en/github/receiving-notifications-about-activity-on-github/choosing-the-delivery-method-for-your-notifications they mention how to restrict emails to receive only failed workflow runs, hope this is what you are looking for or at least it helps ;)

**Comment by maelle** [comment]
> In this link https://help.github.com/en/github/receiving-notifications-about-activity-on-github/choosing-the-delivery-method-for-your-notifications they mention how to restrict emails to receive only failed workflow runs, hope this is what you are looking for or at least it helps ;)

Thanks! I only get web notifications from GitHub (using beta notifications). The url checks action is not a failed run, so I'll need to remind myself (with a calendar or so) to go look at its log on the 1st of each month. Not that bad, really!

**Comment by vsoch** [comment]
@maelle the PR here https://github.com/urlstechie/urlchecker-python/pull/28 will add the `--files` option that will let you derive a list in any way that you see fit, and then run the checker just for each of the files. Once that PR is merged, the container is automatically built to Quay.io, and that means I can open a PR on this repository (it's actually all ready to go!) that exposes the --files argument. Stay tuned! We need @SuperKogito to approve the PR first.

**Comment by vsoch** [comment]
@maelle the action is updated here to allow you to specify `include_files` - would you care to test it out? I'd recommend a workflow step that first derives a comma separated list (no spaces!) of files and/or patterns, and then runs the action in the next step (version 0.1.9) using that set parameter. if you get something working please ping and share the example so we can provide it here for other users to use!

**Comment by maelle** [comment]
Thanks a lot, I'll do that, probably next week though. The links in https://github.com/urlstechie/urlchecker-action/issues/44#issuecomment-611998894 will help me a lot (unless I go with the API and jq).

**Comment by maelle** [comment]
Just for info I went with the API and jq.
Pro: It doesn't require me to clone all branches/history to get the changed files.
Con: it's limited to 30 files. In my case PRs won't change more than 30 files but who knows.

**Comment by maelle** [comment]
I'll add https://github.com/r-hub/docs/blob/master/.github/workflows/pr.yml to the examples repo, I think this can be closed, thanks a ton!
