### ISSUE TITLE
Should git_path default to current repo?

### ISSUE THREAD

**Issue by maelle** [urlstechie/urlchecker-action#46]
this way it'd be easier to copy-paste the workflow file from one repo to another (a lazy question, yes).

**Comment by vsoch** [comment]
If you don’t set it it assumes the current repository and branch that are checked out, yes. That variable is there if you want to run URL checker for a different repository then the action is running in. There is the same variable for branch.

**Comment by maelle** [comment]
So if I don't set it I need to first run the checkout action, now I get it :woman_facepalming: thanks and sorry
