### ISSUE TITLE
false positive link

### ISSUE THREAD

**Issue by shahzebsiddiqui** [urlstechie/urlchecker-action#6]
hi @SuperKogito 

I seem to have a link reported to have been broken see https://github.com/HPC-buildtest/buildtest-framework/runs/428310246?check_suite_focus=true but in reality it is working.

The actual link is https://www.hpcwire.com/2019/01/17/pfizer-hpc-engineer-aims-to-automate-software-stack-testing/ which is found but the url-checker is stating it is not found. I see a red X next to it.

I am using v0.1.2
![image](https://user-images.githubusercontent.com/12942230/73957719-c72b6d00-48d4-11ea-903c-88dcf664e5ff.png)

**Comment by SuperKogito** [comment]
Hello @shahzebsiddiqui  
Thanks for reporting this, I think the error is due to short timeout on the url requests check but I need to further investigate. In the meantime you can upgrade to version 0.1.3 and use the `white_listed_urls` option to hide false positives.

**Comment by shahzebsiddiqui** [comment]
yea i can do that for time being. It's not a big deal right now. Will close this and wanted to inform you about this bug.
