### ISSUE TITLE
URL vs link checking

### ISSUE THREAD

**Issue by maelle** [urlstechie/urlchecker-action#60]
Some more user feedback/questions :wink: With the current action&library, URLs are checked but not links: if you typed `[a cool post](htttps://blabla.org)` by mistake, the wrong link (should be `https://blabla.org`) won't be caught. In Markdown/html files, "links" are well-defined (in comments in code, I agree, less so).

Other actions focus on link checking, I wonder whether this could be added to this action somehow, or as a limitation to the docs maybe. 

(I suppose this is partly the Commonmark debate again ;-))

Maybe a good workflow for a website/thing is

* check links and URLs when content is created;

* check URLs once in a while (the URL can get broken, a link that's not malformed won't change).

Advantages of your library/action: retry, artifact, UA. But do I use another library/action for checking links? :thinking:

**Comment by maelle** [comment]
Note that your action/library is still the only one I see with retry and the ability to pass given filenames. Others also don't have a CSV report as far as I could tell.

**Comment by vsoch** [comment]
I don’t think the action is scoped to handle gross spells errors (eg httpppps). What action / issue specifically do you want addressed for this issue?

**Comment by maelle** [comment]
Checking that all links that are not relative links are URLs, I suppose. I am wondering about link checking because it's a limitation of this action compared to other link checking actions. At the same time most often people 1) copy paste URLs from the browser I suppose 2) see the typo when reviewing, so maybe not that big of a limitation.

**Comment by vsoch** [comment]
This is out of scope for now, I don’t see how we could derive spelling mistakes easily. Urlchecker is optimized for checking urls.
