### ISSUE TITLE
Make it easier to look through real-life examples?

### ISSUE THREAD

**Issue by maelle** [urlstechie/urlchecker-action#62]
Could the list of examples at the end of the README be a table with

* community name, linking to repo as it is now the case
* workflow file presented as `[workflow running blablabla every blablabla](permalink to workflow file)`
* example log?

I'm asking because that's what I go look for in example repos.

**Comment by SuperKogito** [comment]
This sounds nice and it would be better aesthetically. Do you want to take on this? :p I think me and @vsoch got enough at our plates atm.

**Comment by maelle** [comment]
Related: https://github.com/sindresorhus/refined-github/issues/3008
