### ISSUE TITLE
Next release should use tagged container version

### ISSUE THREAD

**Issue by vsoch** [urlstechie/urlchecker-action#65]
We've been doing releases with the `latest` tag, but since this is a moving target and features available are starting to change, I want to transition to having releases here associated with a particular tag/release for urlchecker. For the next round of tests to go in to address adding more tests, we can do a release associated with 0.0.19.

**Comment by SuperKogito** [comment]
I agree to this even though we will have to do some version management and add tests across different versions to make sure everything works.

**Comment by vsoch** [comment]
Fixed with #67, which now uses 0.0.20 release.
