### ISSUE TITLE
variable substitution in url field

### ISSUE THREAD

**Issue by shahzebsiddiqui** [urlstechie/urlchecker-action#7]
Hello,

We have a PR in progress in easybuild see https://github.com/easybuilders/easybuild/pull/591 One of the issues we have is URL-checker can't accept variable substitution. We have configuration files (``.eb``) that build the http url based on few parameters that include `version`  to fetch the tarball for compilation.

Is it possible to fix this issue or is only workaround to ignore these using white list. Can we white list by extension instead of by each filename.

**Comment by SuperKogito** [comment]
I am not sure what do you mean by variable substitution. I get that you automatically generate your links but  what do you mean by "URL-checker can't accept variable substitution"?.  In case you have an idea for a feature, I suggest you open a new issue for a feature request with a clear description of what do you need? and what does it do? with some examples preferably, so I can understand the use case and be able to implement it. You are also welcome to contribute if you already have an idea how to implement it.

As for your second question concerning a workaround, yes, you can white list using an extension, a pattern or even a key-phrase/ word, using the `white_listed_patterns` variable.  Currently the code [checks](https://github.com/SuperKogito/URLs-checker/blob/0d770546a642472ca478a8fa8f3773e57cc2012f/check.py#L33) if a pattern is in the link and if so it is white listed.
```
# check white listed patterns
i = 0
while i < len(white_listed_patterns):
  if white_listed_patterns[i] in url:
      return True
  i += 1
```
The pattern can be a phrase, a base link or a key-word (which can be an extension).
