### ISSUE TITLE
failed to build docker container 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [urlstechie/urlchecker-action#78]
I just noticed it failed to build docker container today as part of the github workflow. I have been using the same version (v0.2.3) for some time and it was working fine.

See https://github.com/buildtesters/buildtest/pull/699/checks?check_run_id=2170371755 

My urlcheck workflow can be found at https://github.com/buildtesters/buildtest/blob/devel/.github/workflows/urlchecker.yml

**Comment by vsoch** [comment]
quay.io is down, so any action that relies on it for containers will fail. https://status.quay.io/. Check back to that interface and try a re-run when it's up again!

**Comment by vsoch** [comment]
If you look at the error, you can see the 502 bad gateway when trying to pull the container:
![image](https://user-images.githubusercontent.com/814322/112069389-59baba00-8b31-11eb-862d-e7f40cf3f575.png)

**Comment by shahzebsiddiqui** [comment]
thanks @vsoch that makes sense now. I will close this issue.
